### ISSUE TITLE
[Complemento de Dados] Modificar campos

### ISSUE THREAD

**Issue by Maegima** [UnifespCodeLab/teapp-api#1]
# História de Usuário

Os campos da API devem ser alterados para que seja possível armazenar informações de professores e especialistas em TEA.

# Resumo

Existem dois tipos de usuários para o Teapp professores e especialistas.
Geral:
- Universidade; 
- Campus; 
- Setor; 
- Gênero; 
- Possui deficiência;
    - Qual; 
- Parente com TEA;
    - Parentesco;
    - Frequência de convívio;

Professores:
- Quantos alunos já teve com TEA;

Especialistas: 
- Há quanto tempo atende pacientes com TEA;
- Em média quantos pacientes com TEA atende por ano;

# Critérios de Aceite

- [ ] Remover campos não utilizados;
- [ ] Adicionar os campos listados na descrição.

# Protótipo

# Informações Adicionais

**Comment by dsalexan** [comment]
Closed via #5 approval
