### ISSUE TITLE
[Formulário socioeconômico] Remover

### ISSUE THREAD

**Issue by Maegima** [UnifespCodeLab/teapp-api#2]
# História de Usuário

Não será necessário um formulário socioeconômico para o Teapp.

# Resumo

Remover a tabela de formulário socioeconômico.

# Critérios de Aceite

- [ ] Remover formulário e endpoints relacionados.
# Protótipo

# Informações Adicionais

**Comment by dsalexan** [comment]
Closed via #5 approval
