### ISSUE TITLE
[Bairros] Remover

### ISSUE THREAD

**Issue by Maegima** [UnifespCodeLab/teapp-api#3]
# História de Usuário

Não será necessário a tabela de bairros para o Teapp. 

# Resumo

Remover os endpoints e tabela relacionados aos Bairros;

# Critérios de Aceite

- [ ] Remover tabela de bairros e endpoints relacionados.

# Protótipo

# Informações Adicionais

**Comment by DanielSalis** [comment]
Foram executadas as seguintes queries:
```sql
ALTER TABLE usuarios 
DROP COLUMN bairro;
```

```sql
DROP TABLE bairros;
```

**Comment by dsalexan** [comment]
Closed via #8 approval
